### ISSUE TITLE
Request to support Bitbucket access tokens for authentication

### ISSUE THREAD

**Issue by ravindrakmr** [turbot/steampipe-plugin-bitbucket#81]
This feature request is to support Bitbucket access tokens to authenticate the connection to Bitbucket cloud. Here is the reference - https://bitbucket.org/blog/access-your-bitbucket-cloud-repositories-more-securely-with-resource-scoped-access-tokens

**Comment by cbruno10** [comment]
HI @ravindrakmr , thanks for opening this request!

Looking in the Bitbucket Go SDK we use, it seems like this authentication method is supported (https://github.com/ktrysmt/go-bitbucket/issues/41#issuecomment-411274913).

I think adding a new config arg called `access_token` with a matching env var `BITBUCKET_ACCESS_TOKEN` (unless the standard is `BITBUCKET_TOKEN` instead, but I haven't found any references so far) would be a sensible design.

This feature isn't something we're likely to take up at the moment due to other priorities, but if anyone is interested in trying to add support in a PR, we're happy to help answer questions/provide suggestions along the way.
